import{a as w,S,i}from"./assets/vendor-DuKcLXOA.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&l(d)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const u=async(s,e)=>{const o={key:"56220585-56a0c3bb81d566663f8c5eae4",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};return(await w.get("https://pixabay.com/api/",{params:o})).data},m=document.querySelector(".gallery"),p=document.querySelector(".loading-span"),f=document.querySelector(".load-more"),q=new S(".gallery-link",{captionDelay:250,animationSpeed:200});function $(){m.innerHTML=""}function h(){p.classList.add("is-active")}function g(){p.classList.remove("is-active")}function y(s){const e=s.map(o=>`
            <li class="gallery-card">
                <a href="${o.largeImageURL}" class="gallery-link">
                    <img class="gallery-img" src="${o.webformatURL}" alt="${o.tags}"
                    />
                    <div class="info">
                        <p class="info-item"><b>Likes</b> ${o.likes}</p>
                        <p class="info-item"><b>Views</b> ${o.views}</p>
                        <p class="info-item"><b>Comments</b> ${o.comments}</p>
                        <p class="info-item"><b>Downloads</b> ${o.downloads}</p>
                    </div>
                </a>
            </li>
        `).join("");m.insertAdjacentHTML("beforeend",e),q.refresh()}function L(){f.classList.add("is-active")}function b(){f.classList.remove("is-active")}const B=document.querySelector(".load-more"),a=document.querySelector("form");let c=1,n,v=0;const M=async s=>{try{if(s.preventDefault(),n=a.elements.search_text.value.trim(),!n){i.error({message:"Input cant be empty!",position:"topCenter"});return}$(),b(),h(),c=1;const e=await u(n,c);if(!e.hits.length){i.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please, try again!"}),a.elements.search_text.placeholder=`${n}`,a.reset();return}v=Math.ceil(e.totalHits/15),e.totalHits>15?L():i.info({message:"You have reached the end of search results!",timeout:5e3,position:"topLeft"}),y(e.hits),a.elements.search_text.placeholder=`${n}`,a.reset()}catch(e){i.error({message:"Something went wrong!",position:"topRight"}),console.log(e)}finally{g()}},P=async s=>{try{c++,b(),h();const e=await u(n,c);if(y(e.hits),x(),c>=v){i.info({message:"You have reached the end of search results!",timeout:5e3,position:"topLeft"});return}L()}catch{i.error({message:"Something went wrong!",position:"topRight"})}finally{g()}};function x(){const s=document.querySelector(".gallery-card");if(!s)return;const e=s.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}a.addEventListener("submit",M);B.addEventListener("click",P);
//# sourceMappingURL=index.js.map
